import type { IndiaRegion } from "./types";

/** Major Indian regions with climate-zone metadata for agent analysis */
export const INDIA_REGIONS: IndiaRegion[] = [
  {
    id: "delhi-ncr",
    name: "Delhi NCR",
    state: "Delhi",
    city: "New Delhi",
    lat: 28.6139,
    lon: 77.209,
    climateZone: "semi-arid",
    childPopulationShare: 0.28,
    primaryRisks: ["heatwave", "air-pollution", "dengue", "water-stress"],
    monsoonMonths: [7, 8, 9],
  },
  {
    id: "mumbai",
    name: "Mumbai Metropolitan",
    state: "Maharashtra",
    city: "Mumbai",
    lat: 19.076,
    lon: 72.8777,
    climateZone: "coastal-tropical",
    childPopulationShare: 0.22,
    primaryRisks: ["flooding", "dengue", "leptospirosis", "heat-humidity"],
    monsoonMonths: [6, 7, 8, 9],
  },
  {
    id: "chennai",
    name: "Chennai & Tamil Nadu Coast",
    state: "Tamil Nadu",
    city: "Chennai",
    lat: 13.0827,
    lon: 80.2707,
    climateZone: "coastal-tropical",
    childPopulationShare: 0.24,
    primaryRisks: ["cyclone", "heatwave", "dengue", "water-scarcity"],
    monsoonMonths: [10, 11, 12],
  },
  {
    id: "kolkata",
    name: "Kolkata & Gangetic Delta",
    state: "West Bengal",
    city: "Kolkata",
    lat: 22.5726,
    lon: 88.3639,
    climateZone: "humid-subtropical",
    childPopulationShare: 0.23,
    primaryRisks: ["flooding", "dengue", "diarrhea", "heat-humidity"],
    monsoonMonths: [6, 7, 8, 9],
  },
  {
    id: "bengaluru",
    name: "Bengaluru Urban",
    state: "Karnataka",
    city: "Bengaluru",
    lat: 12.9716,
    lon: 77.5946,
    climateZone: "tropical-savanna",
    childPopulationShare: 0.21,
    primaryRisks: ["heatwave", "dengue", "water-stress", "air-pollution"],
    monsoonMonths: [6, 7, 8, 9],
  },
  {
    id: "hyderabad",
    name: "Hyderabad & Telangana",
    state: "Telangana",
    city: "Hyderabad",
    lat: 17.385,
    lon: 78.4867,
    climateZone: "semi-arid",
    childPopulationShare: 0.25,
    primaryRisks: ["heatwave", "dengue", "water-stress", "air-pollution"],
    monsoonMonths: [6, 7, 8, 9],
  },
  {
    id: "ahmedabad",
    name: "Ahmedabad & Gujarat",
    state: "Gujarat",
    city: "Ahmedabad",
    lat: 23.0225,
    lon: 72.5714,
    climateZone: "arid",
    childPopulationShare: 0.26,
    primaryRisks: ["extreme-heat", "drought", "heat-stroke", "water-stress"],
    monsoonMonths: [7, 8, 9],
  },
  {
    id: "lucknow",
    name: "Lucknow & Indo-Gangetic Plain",
    state: "Uttar Pradesh",
    city: "Lucknow",
    lat: 26.8467,
    lon: 80.9462,
    climateZone: "humid-subtropical",
    childPopulationShare: 0.32,
    primaryRisks: ["heatwave", "dengue", "diarrhea", "air-pollution"],
    monsoonMonths: [7, 8, 9],
  },
  {
    id: "patna",
    name: "Patna & Bihar",
    state: "Bihar",
    city: "Patna",
    lat: 25.5941,
    lon: 85.1376,
    climateZone: "humid-subtropical",
    childPopulationShare: 0.35,
    primaryRisks: ["flooding", "heatwave", "diarrhea", "malnutrition"],
    monsoonMonths: [7, 8, 9],
  },
  {
    id: "guwahati",
    name: "Guwahati & Northeast",
    state: "Assam",
    city: "Guwahati",
    lat: 26.1445,
    lon: 91.7362,
    climateZone: "humid-subtropical",
    childPopulationShare: 0.29,
    primaryRisks: ["flooding", "landslide", "dengue", "diarrhea"],
    monsoonMonths: [6, 7, 8, 9],
  },
  {
    id: "jaipur",
    name: "Jaipur & Rajasthan",
    state: "Rajasthan",
    city: "Jaipur",
    lat: 26.9124,
    lon: 75.7873,
    climateZone: "arid",
    childPopulationShare: 0.30,
    primaryRisks: ["extreme-heat", "drought", "heat-stroke", "dust-storms"],
    monsoonMonths: [7, 8, 9],
  },
  {
    id: "kochi",
    name: "Kochi & Kerala Coast",
    state: "Kerala",
    city: "Kochi",
    lat: 9.9312,
    lon: 76.2673,
    climateZone: "coastal-tropical",
    childPopulationShare: 0.22,
    primaryRisks: ["flooding", "dengue", "leptospirosis", "heat-humidity"],
    monsoonMonths: [6, 7, 8, 9],
  },
];

export function getIndiaRegion(id: string): IndiaRegion | undefined {
  return INDIA_REGIONS.find((r) => r.id === id);
}

export function getDefaultIndiaRegion(): IndiaRegion {
  return INDIA_REGIONS[0];
}
