import type { IndiaRegion } from "./types";

/** Indian urban regions by tier with climate-zone metadata for agent analysis */
export const INDIA_REGIONS: IndiaRegion[] = [
  // —— Tier 1 metros ——
  {
    id: "delhi-ncr",
    name: "Delhi NCR",
    state: "Delhi",
    city: "New Delhi",
    lat: 28.6139,
    lon: 77.209,
    tier: 1,
    climateZone: "semi-arid",
    childPopulationShare: 0.28,
    primaryRisks: ["heatwave", "air-pollution", "dengue", "water-stress"],
    monsoonMonths: [7, 8, 9],
  },
  {
    id: "mumbai",
    name: "Mumbai Metropolitan",
    state: "Maharashtra",
    city: "Mumbai",
    lat: 19.076,
    lon: 72.8777,
    tier: 1,
    climateZone: "coastal-tropical",
    childPopulationShare: 0.22,
    primaryRisks: ["flooding", "dengue", "leptospirosis", "heat-humidity"],
    monsoonMonths: [6, 7, 8, 9],
  },
  {
    id: "bengaluru",
    name: "Bengaluru Urban",
    state: "Karnataka",
    city: "Bengaluru",
    lat: 12.9716,
    lon: 77.5946,
    tier: 1,
    climateZone: "tropical-savanna",
    childPopulationShare: 0.21,
    primaryRisks: ["heatwave", "dengue", "water-stress", "air-pollution"],
    monsoonMonths: [6, 7, 8, 9],
  },
  {
    id: "hyderabad",
    name: "Hyderabad & Telangana",
    state: "Telangana",
    city: "Hyderabad",
    lat: 17.385,
    lon: 78.4867,
    tier: 1,
    climateZone: "semi-arid",
    childPopulationShare: 0.25,
    primaryRisks: ["heatwave", "dengue", "water-stress", "air-pollution"],
    monsoonMonths: [6, 7, 8, 9],
  },
  {
    id: "chennai",
    name: "Chennai & Tamil Nadu Coast",
    state: "Tamil Nadu",
    city: "Chennai",
    lat: 13.0827,
    lon: 80.2707,
    tier: 1,
    climateZone: "coastal-tropical",
    childPopulationShare: 0.24,
    primaryRisks: ["cyclone", "heatwave", "dengue", "water-scarcity"],
    monsoonMonths: [10, 11, 12],
  },
  {
    id: "kolkata",
    name: "Kolkata & Gangetic Delta",
    state: "West Bengal",
    city: "Kolkata",
    lat: 22.5726,
    lon: 88.3639,
    tier: 1,
    climateZone: "humid-subtropical",
    childPopulationShare: 0.23,
    primaryRisks: ["flooding", "dengue", "diarrhea", "heat-humidity"],
    monsoonMonths: [6, 7, 8, 9],
  },
  {
    id: "ahmedabad",
    name: "Ahmedabad & Gujarat",
    state: "Gujarat",
    city: "Ahmedabad",
    lat: 23.0225,
    lon: 72.5714,
    tier: 1,
    climateZone: "arid",
    childPopulationShare: 0.26,
    primaryRisks: ["extreme-heat", "drought", "heat-stroke", "water-stress"],
    monsoonMonths: [7, 8, 9],
  },
  {
    id: "pune",
    name: "Pune Metropolitan",
    state: "Maharashtra",
    city: "Pune",
    lat: 18.5204,
    lon: 73.8567,
    tier: 1,
    climateZone: "tropical-savanna",
    childPopulationShare: 0.23,
    primaryRisks: ["flooding", "dengue", "heat-humidity", "water-stress"],
    monsoonMonths: [6, 7, 8, 9],
  },

  // —— Tier 2 emerging hubs ——
  {
    id: "lucknow",
    name: "Lucknow & Indo-Gangetic Plain",
    state: "Uttar Pradesh",
    city: "Lucknow",
    lat: 26.8467,
    lon: 80.9462,
    tier: 2,
    climateZone: "humid-subtropical",
    childPopulationShare: 0.32,
    primaryRisks: ["heatwave", "dengue", "diarrhea", "air-pollution"],
    monsoonMonths: [7, 8, 9],
  },
  {
    id: "jaipur",
    name: "Jaipur & Rajasthan",
    state: "Rajasthan",
    city: "Jaipur",
    lat: 26.9124,
    lon: 75.7873,
    tier: 2,
    climateZone: "arid",
    childPopulationShare: 0.3,
    primaryRisks: ["extreme-heat", "drought", "heat-stroke", "dust-storms"],
    monsoonMonths: [7, 8, 9],
  },
  {
    id: "kochi",
    name: "Kochi & Kerala Coast",
    state: "Kerala",
    city: "Kochi",
    lat: 9.9312,
    lon: 76.2673,
    tier: 2,
    climateZone: "coastal-tropical",
    childPopulationShare: 0.22,
    primaryRisks: ["flooding", "dengue", "leptospirosis", "heat-humidity"],
    monsoonMonths: [6, 7, 8, 9],
  },
  {
    id: "surat",
    name: "Surat & South Gujarat",
    state: "Gujarat",
    city: "Surat",
    lat: 21.1702,
    lon: 72.8311,
    tier: 2,
    climateZone: "coastal-tropical",
    childPopulationShare: 0.24,
    primaryRisks: ["flooding", "dengue", "air-pollution", "heat-humidity"],
    monsoonMonths: [6, 7, 8, 9],
  },
  {
    id: "bhubaneswar",
    name: "Bhubaneswar & Odisha Coast",
    state: "Odisha",
    city: "Bhubaneswar",
    lat: 20.2961,
    lon: 85.8245,
    tier: 2,
    climateZone: "coastal-tropical",
    childPopulationShare: 0.27,
    primaryRisks: ["cyclone", "flooding", "dengue", "heat-humidity"],
    monsoonMonths: [6, 7, 8, 9, 10],
  },
  {
    id: "visakhapatnam",
    name: "Visakhapatnam & Andhra Coast",
    state: "Andhra Pradesh",
    city: "Visakhapatnam",
    lat: 17.6868,
    lon: 83.2185,
    tier: 2,
    climateZone: "coastal-tropical",
    childPopulationShare: 0.25,
    primaryRisks: ["cyclone", "heat-humidity", "dengue", "flooding"],
    monsoonMonths: [6, 7, 8, 9, 10],
  },
  {
    id: "indore",
    name: "Indore & Central MP",
    state: "Madhya Pradesh",
    city: "Indore",
    lat: 22.7196,
    lon: 75.8577,
    tier: 2,
    climateZone: "tropical-savanna",
    childPopulationShare: 0.29,
    primaryRisks: ["heatwave", "dengue", "water-stress", "air-pollution"],
    monsoonMonths: [6, 7, 8, 9],
  },
  {
    id: "guwahati",
    name: "Guwahati & Northeast",
    state: "Assam",
    city: "Guwahati",
    lat: 26.1445,
    lon: 91.7362,
    tier: 2,
    climateZone: "humid-subtropical",
    childPopulationShare: 0.29,
    primaryRisks: ["flooding", "landslide", "dengue", "diarrhea"],
    monsoonMonths: [6, 7, 8, 9],
  },
  {
    id: "dehradun",
    name: "Dehradun & Uttarakhand Hills",
    state: "Uttarakhand",
    city: "Dehradun",
    lat: 30.3165,
    lon: 78.0322,
    tier: 2,
    climateZone: "humid-subtropical",
    childPopulationShare: 0.26,
    primaryRisks: ["landslide", "flooding", "cold-stress", "water-contamination"],
    monsoonMonths: [7, 8, 9],
  },
  {
    id: "varanasi",
    name: "Varanasi & Eastern UP",
    state: "Uttar Pradesh",
    city: "Varanasi",
    lat: 25.3176,
    lon: 82.9739,
    tier: 2,
    climateZone: "humid-subtropical",
    childPopulationShare: 0.31,
    primaryRisks: ["flooding", "heatwave", "air-pollution", "diarrhea"],
    monsoonMonths: [7, 8, 9],
  },
  {
    id: "chandigarh",
    name: "Chandigarh & Punjab Plains",
    state: "Chandigarh",
    city: "Chandigarh",
    lat: 30.7333,
    lon: 76.7794,
    tier: 2,
    climateZone: "semi-arid",
    childPopulationShare: 0.24,
    primaryRisks: ["heatwave", "air-pollution", "dengue", "water-stress"],
    monsoonMonths: [7, 8, 9],
  },
  {
    id: "nagpur",
    name: "Nagpur & Vidarbha",
    state: "Maharashtra",
    city: "Nagpur",
    lat: 21.1458,
    lon: 79.0882,
    tier: 2,
    climateZone: "tropical-savanna",
    childPopulationShare: 0.28,
    primaryRisks: ["extreme-heat", "drought", "heat-stroke", "water-stress"],
    monsoonMonths: [6, 7, 8, 9],
  },
  {
    id: "coimbatore",
    name: "Coimbatore & Western Tamil Nadu",
    state: "Tamil Nadu",
    city: "Coimbatore",
    lat: 11.0168,
    lon: 76.9558,
    tier: 2,
    climateZone: "tropical-savanna",
    childPopulationShare: 0.25,
    primaryRisks: ["water-stress", "heatwave", "dengue", "air-pollution"],
    monsoonMonths: [6, 7, 8, 9, 10],
  },
  {
    id: "vadodara",
    name: "Vadodara & Central Gujarat",
    state: "Gujarat",
    city: "Vadodara",
    lat: 22.3072,
    lon: 73.1812,
    tier: 2,
    climateZone: "semi-arid",
    childPopulationShare: 0.27,
    primaryRisks: ["flooding", "heatwave", "dengue", "water-stress"],
    monsoonMonths: [6, 7, 8, 9],
  },
  {
    id: "thiruvananthapuram",
    name: "Thiruvananthapuram & South Kerala",
    state: "Kerala",
    city: "Thiruvananthapuram",
    lat: 8.5241,
    lon: 76.9366,
    tier: 2,
    climateZone: "coastal-tropical",
    childPopulationShare: 0.23,
    primaryRisks: ["flooding", "cyclone", "dengue", "heat-humidity"],
    monsoonMonths: [6, 7, 8, 9],
  },
  {
    id: "bhopal",
    name: "Bhopal & Central MP",
    state: "Madhya Pradesh",
    city: "Bhopal",
    lat: 23.2599,
    lon: 77.4126,
    tier: 2,
    climateZone: "tropical-savanna",
    childPopulationShare: 0.3,
    primaryRisks: ["heatwave", "flooding", "dengue", "water-stress"],
    monsoonMonths: [6, 7, 8, 9],
  },
  {
    id: "amritsar",
    name: "Amritsar & Punjab Border",
    state: "Punjab",
    city: "Amritsar",
    lat: 31.634,
    lon: 74.8723,
    tier: 2,
    climateZone: "semi-arid",
    childPopulationShare: 0.29,
    primaryRisks: ["heatwave", "air-pollution", "cold-stress", "water-stress"],
    monsoonMonths: [7, 8, 9],
  },
  {
    id: "raipur",
    name: "Raipur & Chhattisgarh",
    state: "Chhattisgarh",
    city: "Raipur",
    lat: 21.2514,
    lon: 81.6296,
    tier: 2,
    climateZone: "tropical-savanna",
    childPopulationShare: 0.32,
    primaryRisks: ["heatwave", "malnutrition", "dengue", "flooding"],
    monsoonMonths: [6, 7, 8, 9],
  },

  // —— Tier 3 district & regional centres ——
  {
    id: "patna",
    name: "Patna & Bihar",
    state: "Bihar",
    city: "Patna",
    lat: 25.5941,
    lon: 85.1376,
    tier: 3,
    climateZone: "humid-subtropical",
    childPopulationShare: 0.35,
    primaryRisks: ["flooding", "heatwave", "diarrhea", "malnutrition"],
    monsoonMonths: [7, 8, 9],
  },
  {
    id: "ranchi",
    name: "Ranchi & Jharkhand Plateau",
    state: "Jharkhand",
    city: "Ranchi",
    lat: 23.3441,
    lon: 85.3096,
    tier: 3,
    climateZone: "humid-subtropical",
    childPopulationShare: 0.33,
    primaryRisks: ["heatwave", "malnutrition", "water-stress", "diarrhea"],
    monsoonMonths: [6, 7, 8, 9],
  },
  {
    id: "srinagar",
    name: "Srinagar & Kashmir Valley",
    state: "Jammu & Kashmir",
    city: "Srinagar",
    lat: 34.0837,
    lon: 74.7973,
    tier: 3,
    climateZone: "humid-subtropical",
    childPopulationShare: 0.28,
    primaryRisks: ["flooding", "landslide", "cold-stress", "water-contamination"],
    monsoonMonths: [7, 8, 9],
  },
  {
    id: "kanpur",
    name: "Kanpur & Upper Ganga",
    state: "Uttar Pradesh",
    city: "Kanpur",
    lat: 26.4499,
    lon: 80.3319,
    tier: 3,
    climateZone: "humid-subtropical",
    childPopulationShare: 0.3,
    primaryRisks: ["heatwave", "flooding", "air-pollution", "diarrhea"],
    monsoonMonths: [7, 8, 9],
  },
  {
    id: "agra",
    name: "Agra & Doab",
    state: "Uttar Pradesh",
    city: "Agra",
    lat: 27.1767,
    lon: 78.0081,
    tier: 3,
    climateZone: "semi-arid",
    childPopulationShare: 0.31,
    primaryRisks: ["extreme-heat", "air-pollution", "water-stress", "heat-stroke"],
    monsoonMonths: [7, 8, 9],
  },
  {
    id: "jodhpur",
    name: "Jodhpur & Marwar",
    state: "Rajasthan",
    city: "Jodhpur",
    lat: 26.2389,
    lon: 73.0243,
    tier: 3,
    climateZone: "arid",
    childPopulationShare: 0.32,
    primaryRisks: ["extreme-heat", "drought", "heat-stroke", "dust-storms"],
    monsoonMonths: [7, 8, 9],
  },
  {
    id: "gorakhpur",
    name: "Gorakhpur & Purvanchal",
    state: "Uttar Pradesh",
    city: "Gorakhpur",
    lat: 26.7606,
    lon: 83.3732,
    tier: 3,
    climateZone: "humid-subtropical",
    childPopulationShare: 0.34,
    primaryRisks: ["flooding", "dengue", "diarrhea", "malnutrition"],
    monsoonMonths: [7, 8, 9],
  },
  {
    id: "madurai",
    name: "Madurai & South Tamil Nadu",
    state: "Tamil Nadu",
    city: "Madurai",
    lat: 9.9252,
    lon: 78.1198,
    tier: 3,
    climateZone: "semi-arid",
    childPopulationShare: 0.27,
    primaryRisks: ["water-scarcity", "heatwave", "dengue", "water-stress"],
    monsoonMonths: [10, 11, 12],
  },
  {
    id: "tiruchirappalli",
    name: "Tiruchirappalli & Cauvery Delta",
    state: "Tamil Nadu",
    city: "Tiruchirappalli",
    lat: 10.7905,
    lon: 78.7047,
    tier: 3,
    climateZone: "tropical-savanna",
    childPopulationShare: 0.26,
    primaryRisks: ["drought", "water-stress", "heatwave", "dengue"],
    monsoonMonths: [10, 11, 12],
  },
  {
    id: "jammu",
    name: "Jammu & Jammu Plains",
    state: "Jammu & Kashmir",
    city: "Jammu",
    lat: 32.7266,
    lon: 74.857,
    tier: 3,
    climateZone: "humid-subtropical",
    childPopulationShare: 0.29,
    primaryRisks: ["flooding", "landslide", "heatwave", "cold-stress"],
    monsoonMonths: [7, 8, 9],
  },
  {
    id: "siliguri",
    name: "Siliguri & Terai Foothills",
    state: "West Bengal",
    city: "Siliguri",
    lat: 26.7271,
    lon: 88.3953,
    tier: 3,
    climateZone: "humid-subtropical",
    childPopulationShare: 0.3,
    primaryRisks: ["flooding", "landslide", "dengue", "diarrhea"],
    monsoonMonths: [6, 7, 8, 9],
  },
];

export const INDIA_TIER_LABELS: Record<IndiaRegion["tier"], string> = {
  1: "Tier 1 — Metros",
  2: "Tier 2 — Emerging hubs",
  3: "Tier 3 — Regional centres",
};

export function getIndiaRegion(id: string): IndiaRegion | undefined {
  return INDIA_REGIONS.find((r) => r.id === id);
}

export function getDefaultIndiaRegion(): IndiaRegion {
  return INDIA_REGIONS[0];
}

export function getIndiaRegionsByTier(tier: IndiaRegion["tier"]): IndiaRegion[] {
  return INDIA_REGIONS.filter((r) => r.tier === tier);
}
